feat: 푸시발송, 푸시 사운드 수정 API
luckkids/luckkids-server pull request #146
Opened 2024-02-27 08:41 UTC by SangkiHan

푸시발송 적용 API
1. 공지사항 등록 API
2. 버전등록 API
3. 친구코드로 친구추가 API
4. 럭키즈 미션 등록 API

지금 ScreenName 정해진게 없어서 클라분들께 말씀드려서 정리해야합니다.

지금 PR올린거는 서브모듈에 FCM json파일 잘 복사 되는지 테스트 해보기 위함입니다!

2024-02-28 02:02 UTC, mingeonho1 requested changes
수고하셨습니다 !

2024-02-28 02:02 UTC, mingeonho1 commented on src/main/java/com/luckkids/domain/push/PushRepository.java
> +    List<Push> findByAlertSetting_LuckMessage(AlertStatus alertStatus);
쿼리 DSL로 동적으로 바뀌는게 좋을 것 같아요 ! (service에서 이어지는 코멘트)

2024-02-28 07:02 UTC, mingeonho1 commented on src/main/java/com/luckkids/config/FCMConfig.java
> +}
리팩토링 버전은 참고만 부탁드려요

2024-03-26 08:41 UTC, SangkiHan commented
Slack으로 클라이언트 분들께 알림내역 관련해서 여쭤봤는데 답변오면 공지사항 버전 URL어떻게 할 지 결정하겠슴돠

2024-04-12 04:01 UTC, merged